name: first_project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  google_fonts: ^1.0.0

  get_it: ^4.0.0
  provider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: assets/fonts/Schyler-Regular.ttf
    #     - asset: assets/fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: assets/fonts/TrajanPro.ttf
    #     - asset: assets/fonts/TrajanPro_Bold.ttf
    #       weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
    # - family: RobotoMono
    #   fonts:
    #     - asset: assets/fonts/RobotoMono-Regular.ttf
    #     - asset: assets/fonts/RobotoMono-Bold.ttf
    #       weight: 700
uses-material-design: true
